extends Node

signal time_transition_0
signal time_transition_1
signal time_transition_2
signal time_transition_3
signal time_transition_4
signal time_transition_5
signal time_transition_6
signal time_transition_7
signal time_transition_8
signal time_transition_9

